name: WBTC
version: '${project.version}'
main: de.wbtc.mcplugin.WBTC
authors: [Julian Bruyers]
description: A simple Minecraft survival bukkit/paper server enhancement plugin.
website: https://www.github.com/julian-bruyers/mc-wbtc
api-version: '1.21'
commands:
  wbtc:
    description: Get information about the plugin.
    usage: "/wbtc"
    aliases: [wbtcinfo]
    permission:
    permission-message:
  friend:
    description: Manage your friends.
    usage: "/friend add/remove/accept/deny <player> or /friend list or /friend requests also (@a for <player> addresses all players)"
    aliases:
    permission:
    permission-message:
  enderchest:
    description: Open your enderchest or another players enderchest when giving their name (Only works with friends).
    usage: "/enderchest (<player>)"
    aliases: [ec]
    permission:
    permission-message:
  gm:
    description: Change your gamemode.
    usage: "/gm <0/1/2/3>"
    aliases:
    permission:
    permission-message:
  position:
    description: Broadcast your positions to your friends or get a friends position.
    usage: "/position (broadcasts your position to all your friends) /position <player> (gets the position of a friend)"
    aliases: [pos]
    permission:
    permission-message:
permissions:
    wbtc.info:
        description: Permission to use the full info command.
        default: op
    wbtc.friend:
        description: Permission to use the friend command.
        default: op
    wbtc.enderchest.self:
        description: Permission to open your own enderchest.
        default: op
    wbtc.enderchest.other:
        description: Permission to open other players enderchest.
        default: op
    wbtc.gamemode.survival:
        description: Permission to change your gamemode to survival.
        default: op
    wbtc.gamemode.creative:
        description: Permission to change your gamemode to creative.
        default: op
    wbtc.gamemode.adventure:
        description: Permission to change your gamemode to adventure.
        default: op
    wbtc.gamemode.spectator:
        description: Permission to change your gamemode to spectator.
        default: op
    wbtc.position:
        description: Permission to use the position command.
        default: op